pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions:
      - base=master
      - status-success=continuous-integration/travis-ci/pr
      - status-success=codecov/project
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~="^WIP:"
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: merge
        strict: true
        strict_method: rebase
