# modules.toml - Flux module and rc task configuration
#
# Supported keys:
#
# modules: Array of modules config entries, supporting the following keys:
#
#   name     (required) The module name. This will be the target of module load
#            and remove requests. If there is a name collision between entries,
#            then the last one loaded will be used.
#
#   provides (optional) List of services this module provides, e.g. "sched".
#             If multiple modules provide the same service name, the last one
#             loaded takes precedence by default, though this can be influenced
#             by configuration or broker attributes.
#
#   args     (optional) An array of module arguments.
#
#   ranks    (optional) The set of ranks on this module should be loaded.
#            May either be an RFC 22 idset string, or a string beginning with
#            `>` or `<` followed by a single integer. (e.g. ">0" to load a
#            module on all ranks but rank 0.
#
#   requires  (optional) An array of services this module requires, i.e. if
#             this module is loaded then services/modules in requires will also
#             be loaded. If this module also has to be loaded after any
#             required modules, add them to the after array as well.
#
#   after     (optional) An array of modules for which this module must be
#             loaded after. If this module also requires the service or module
#             it is loaded after, then the module must also be added to
#             `requires`.
#
#   needs     (optional) An array of modules which should disable this module
#             if they are not loaded.
#
#   requires-config (optional) An array of configuration keys in dotted key
#                   form which are required for this module to be loaded.
#                   If the key is not set, then the module is skipped.
#
#   requires-attrs  (optional) Same as with requires-config, but for broker
#                   attributes.
#
#

[[modules]]
name = "barrier"

[[modules]]
name = "heartbeat"
ranks = "0"

[[modules]]
name = "content"
requires = ["heartbeat"]

[[modules]]
name = "cron"
ranks = "0"
requires = ["heartbeat"]
args = ["sync=heartbeat.pulse"]

[[modules]]
name = "content-s3"
ranks = "0"
after = [ "content" ]
requires = [ "content" ]
provides = [ "content-backing" ]

[[modules]]
name = "content-files"
ranks = "0"
after = [ "content" ]
requires = [ "content" ]
provides = [ "content-backing" ]

[[modules]]
name = "content-sqlite"
ranks = "0"
after = [ "content" ]
requires = [ "content" ]
provides = [ "content-backing" ]

[[modules]]
name = "kvs"
after = ["content-backing", "content"]
requires = ["content", "heartbeat"]

[[modules]]
name = "kvs-watch"
after = ["kvs"]
requires = ["kvs"]

[[modules]]
name = "sdbus"
requires-config = ["systemd.enable"]

[[modules]]
name = "sdexec"
after = ["sdbus"]
requires = ["sdbus"]
requires-config = ["systemd.enable"]

[[modules]]
name = "resource"
after = ["kvs-watch"]
requires = ["kvs-watch"]

[[modules]]
name = "job-manager"
ranks = "0"
requires = ["resource", "kvs"]
after = ["resource", "kvs"]

[[modules]]
name = "job-info"
requires = ["kvs-watch", "kvs"]

[[modules]]
name = "job-list"
ranks = "0"
requires = ["job-manager"]
after = ["job-manager"]

[[modules]]
name = "job-ingest"
after = ["job-manager"]
requires = ["kvs", "job-manager"]

[[modules]]
name = "job-exec"
after = ["job-manager"]
requires = ["kvs", "job-manager"]
ranks = "0"

[[modules]]
name = "sched-simple"
provides = ["sched", "feasibility"]
after = ["job-manager", "resource"]
requires = ["job-manager", "resource"]
ranks = "0"
