#!/bin/sh -e

RANK=$(FLUX_LOCAL_CONNECTOR_RETRY_COUNT=30 flux getattr rank)
flux modprobe rc1

core_dir=$(cd ${0%/*} && pwd -P)
all_dirs=$core_dir${FLUX_RC_EXTRA:+":$FLUX_RC_EXTRA"}
IFS=:
for rcdir in $all_dirs; do
    for rcfile in $rcdir/rc1.d/*; do
	[ -e $rcfile ] || continue
	echo running $rcfile
        $rcfile
    done
done
